# settings.py
# Archivo generado automaticamente

"""
Django settings for FrameworkDjango project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path # Importando el modulo Path que da una forma de trabajar con rutas de archivos y directorios

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # Almacenando  la ruta absoluta del directorio base del proyecto del objeto Path en la variable BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2ret4ly#jclp=ro5t0i)50u+vom(v*hycra&3-v+0usnya!37l' # Definiendo la variable SECRET_KEY para el cifrado de contraseñas de usuarios

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Definiendo la variable DEBUG para ver si la aplicacion se ejecuta en modo depuracion

ALLOWED_HOSTS = [] # Definiendo la variable ALLOWED_HOSTS para obtener la lista de host o direcciones IP


# Application definition

INSTALLED_APPS = [ # Definiendo la lista INSTALLED_APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [ # Definiendo la lista MIDDLEWARE. Es un código que se ejecuta antes o después de que se procese una solicitud HTTP
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FrameworkDjango.urls' # es el módulo que contiene las rutas URL de la aplicación.

TEMPLATES = [ # Es una lista de diccionarios que especifican cómo se renderizarán las plantillas HTML
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FrameworkDjango.wsgi.application' # Es el punto de entrada de la aplicación para el servidor web


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = { # Este diccionario contiene una sola clave llamada default
    'default': { # Contiene claves para configurar la conexión de la aplicación a la base de datos
        'ENGINE': 'django.db.backends.sqlite3', # Utilizando la base de datos sqlite3
        'NAME': BASE_DIR / 'db.sqlite3', # el archivo de base de datos se encuentra en la ruta BASE_DIR / 'db.sqlite3'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ # Contiene cuatro elementos donde cada un es un diccionario que especifica un validador de contraseña diferente
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # Especifica el idioma predeterminado de la aplicación

TIME_ZONE = 'UTC' # Especifica la zona horaria predeterminada de la aplicación

USE_I18N = True # se utilizan para habilitar la internacionalización

USE_TZ = True # se utilizan para habilitar la zona horaria


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/' # Se utiliza para especificar la URL base para los archivos estáticos de la aplicación

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # se utiliza para especificar el tipo de campo de clave principal predeterminado para los modelos de la aplicación
